### ISSUE TITLE
[FEATURE] add discord bot badge to readme

### ISSUE THREAD

**Issue by kekkodance** [brandongallagher1999/1337x-Bot#104]
https://awesomeopensource.com/project/ashmonty/discord-md-badge

something like this, maybe one with the bot invite link too

**Comment by kekkodance** [comment]
and maybe another one to indicate how many servers its in

**Comment by brandongallagher1999** [comment]
Will need to get approval from monty.

**Comment by brandongallagher1999** [comment]
Monty is not responding, so it's not really worth my time.
