### ISSUE TITLE
choose an actual license

### ISSUE THREAD

**Issue by kekkodance** [brandongallagher1999/1337x-Bot#107]
choosing an actual license like GPLv3 or MIT would be better, github has a nice ui for what you can and cant do with official licenses.

**Comment by kekkodance** [comment]
or update the "2020" inside of the current license file even.

**Comment by pryme-svg** [comment]
the current license lets people use the software in any way as long its not for profit i don't see why its not good

**Comment by brandongallagher1999** [comment]
Correct @pryme-svg
