### ISSUE TITLE
bot crashing after im trying to start it in docker

### ISSUE THREAD

**Issue by TomerGamerTV** [brandongallagher1999/1337x-Bot#29]
i tried to start it but it gives me this error
```
D:\Downloads\1337x-Bot>docker-compose up
Creating network "1337x-bot_default" with the default driver
Creating 1337x-bot_bot_1 ... done
Attaching to 1337x-bot_bot_1
bot_1  | internal/modules/cjs/loader.js:905
bot_1  |   throw err;
bot_1  |   ^
bot_1  |
bot_1  | Error: Cannot find module 'typescript'
bot_1  | Require stack:
bot_1  | - /usr/local/lib/node_modules/ts-node/dist/index.js
bot_1  | - /usr/local/lib/node_modules/ts-node/dist/repl.js
bot_1  | - /usr/local/lib/node_modules/ts-node/dist/bin.js
bot_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
bot_1  |     at Function.resolve (internal/modules/cjs/helpers.js:98:19)
bot_1  |     at loadCompiler (/usr/local/lib/node_modules/ts-node/dist/index.js:151:34)
bot_1  |     at create (/usr/local/lib/node_modules/ts-node/dist/index.js:158:28)
bot_1  |     at Object.register (/usr/local/lib/node_modules/ts-node/dist/index.js:127:21)
bot_1  |     at main (/usr/local/lib/node_modules/ts-node/dist/bin.js:180:29)
bot_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/dist/bin.js:348:5)
bot_1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
bot_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
bot_1  |     at Module.load (internal/modules/cjs/loader.js:950:32) {
bot_1  |   code: 'MODULE_NOT_FOUND',
bot_1  |   requireStack: [
bot_1  |     '/usr/local/lib/node_modules/ts-node/dist/index.js',
bot_1  |     '/usr/local/lib/node_modules/ts-node/dist/repl.js',
bot_1  |     '/usr/local/lib/node_modules/ts-node/dist/bin.js'
bot_1  |   ]
bot_1  | }
1337x-bot_bot_1 exited with code 1
```

**Comment by brandongallagher1999** [comment]
Hello again Tomer,

I have fixed the issue in the Dockerfile and made the commit to the repo.

Thank you for showing so much interest in my bot!

**Comment by TomerGamerTV** [comment]
> Hello again Tomer,
> 
> I have fixed the issue in the Dockerfile and made the commit to the repo.
> 
> Thank you for showing so much interest in my bot!

still not working

```
Starting 1337x-bot_bot_1 ... done
Attaching to 1337x-bot_bot_1
bot_1  | (node:1) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
bot_1  |     at Client.login (/node_modules/discord.js/src/client/Client.js:206:52)
bot_1  |     at Object.<anonymous> (/index.ts:125:8)
bot_1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
bot_1  |     at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1225:23)
bot_1  |     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
bot_1  |     at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1228:12)
bot_1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
bot_1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
bot_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
bot_1  |     at main (/usr/local/lib/node_modules/ts-node/src/bin.ts:330:12)
bot_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/bin.ts:477:3)
bot_1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
bot_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
bot_1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
bot_1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
bot_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
bot_1  |     at internal/main/run_main_module.js:17:47
bot_1  | (Use `node --trace-warnings ...` to show where the warning was created)
bot_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
bot_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by brandongallagher1999** [comment]
The container is running on both my PC and the AWS EC2 instance. Not sure why you're getting this error.

**Comment by TomerGamerTV** [comment]
> The container is running on both my PC and the AWS EC2 instance. Not sure why you're getting this error.

can you try looking into this? maybe you have a different version of docker or something like that?

**Comment by brandongallagher1999** [comment]
It's a strange bug. It runs fine on my machine then when I try to build it in Docker, it fails due to some node dependancy. Strange.

**Comment by TomerGamerTV** [comment]
> It's a strange bug. It runs fine on my machine then when I try to build it in Docker, it fails due to some node dependancy. Strange.

what node version do you have?

**Comment by brandongallagher1999** [comment]
Long Term Support

**Comment by TomerGamerTV** [comment]
> Long Term Support

can you send me the version?

**Comment by brandongallagher1999** [comment]
Hello Tomer,

Sorry for the late reply. All docker problems have been fixed and have been deployed to production and pre-prod. You are now able to run this without problems, given that you have a config.json as specified in the README.md

Brandon

**Comment by TomerGamerTV** [comment]
> Hello Tomer,
> 
> Sorry for the late reply. All docker problems have been fixed and have been deployed to production and pre-prod. You are now able to run this without problems, given that you have a config.json as specified in the README.md
> 
> Brandon

i tried the lastest version for it gave me the same error


```Recreating 1337x-bot_bot_1 ... done
Attaching to 1337x-bot_bot_1
bot_1  | (node:8) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
bot_1  |     at Client.login (/node_modules/discord.js/src/client/Client.js:206:52)
bot_1  |     at Object.<anonymous> (/index.ts:126:8)
bot_1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
bot_1  |     at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1225:23)
bot_1  |     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
bot_1  |     at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1228:12)bot_1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
bot_1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
bot_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
bot_1  |     at main (/usr/local/lib/node_modules/ts-node/src/bin.ts:330:12)
bot_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/bin.ts:477:3)
bot_1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
bot_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
bot_1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
bot_1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
bot_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
bot_1  |     at internal/main/run_main_module.js:17:47
bot_1  | (Use `node --trace-warnings ...` to show where the warning was created)
bot_1  | (node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
bot_1  | (node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by brandongallagher1999** [comment]
That's because you don't have a config.json setup in your repo with a token. The token is passed via a Docker arg, or you make a config.json and put { token: "your token" } inside.

**Comment by TomerGamerTV** [comment]
> That's because you don't have a config.json setup in your repo with a token. The token is passed via a Docker arg, or you make a config.json and put { token: "your token" } inside.

this is how my config looks like:

```
{
  "config" : "NzExNDg2NDM1MjEwODIxNjQy.XsDtYA.XWKja76OH3XkmJ7eBHUkFXADGhI"
}
```

**Comment by brandongallagher1999** [comment]
I'm an idiot, yet again. Inside of config.json, change "config" to "token". I updated the README as well.

**Comment by TomerGamerTV** [comment]
> I'm an idiot, yet again. Inside of config.json, change "config" to "token". I updated the README as well.
1. you are not an idiot because I also did dose type of things like in 80% of my projects so its normal, plus if you didn't mention the config before, you probably wouldn't found the problem

2. I changed the config to token but then testing it didn't work, so I rebuild it, and after running again it's working!
but it looks like it's stuck on `Attaching to 1337x-bot_bot_1` can you add a message saying that the bot is online and working fine and like show in how many servers it's in?

**Comment by brandongallagher1999** [comment]
Yep, I'm going to add that to the TODO list.

**Comment by brandongallagher1999** [comment]
Cool. I implemented your request, and it's in production now. https://imgur.com/a/BhxVpci

**Comment by TomerGamerTV** [comment]
> Cool. I implemented your request, and it's in production now. https://imgur.com/a/BhxVpci

Cool, what about the status for the cmd? because like then you have the bot in more than 100 servers you want to see what is going on right?

**Comment by brandongallagher1999** [comment]
I added the console log which tells you how many servers it's in, as well as adding the server count to the status.

**Comment by TomerGamerTV** [comment]
> I added the console log which tells you how many servers it's in, as well as adding the server count to the status.

so I need to redownload it?
I'm not trying to give you any commands if this is what you think I'm doing but why don't make an auto updater so it will be easier to update the bot?

**Comment by brandongallagher1999** [comment]
You will need to pull from this repo (redownload it I suppose) every time I make a change the to master branch. 

I don't know what you're referring to when you mention an "auto updater"?

**Comment by TomerGamerTV** [comment]
> You will need to pull from this repo (redownload it I suppose) every time I make a change the to master branch.
> 
> I don't know what you're referring to when you mention an "auto updater"?

like then you start the bot it will check for updates and if there is it will automatically download it and relaunch the bot

**Comment by brandongallagher1999** [comment]
So when the dockerfile is read by the Docker Engine, it will copy over all the contents of the repo into the Docker image. Cloning the latest version of the repo inside of the docker image is a bad practice and it's recommended that you first clone the repo then had the docker image build from that. What you want technically could be implemented, but it's bad practice. You're just going to have to git fetch/pull whenever you want the latest version. I'd recommend "watching" this repo for changes and receive notifications upon new commits. Then pull and rebuild your docker image.

**Comment by TomerGamerTV** [comment]
> So when the dockerfile is read by the Docker Engine, it will copy over all the contents of the repo into the Docker image. Cloning the latest version of the repo inside of the docker image is a bad practice and it's recommended that you first clone the repo then had the docker image build from that. What you want technically could be implemented, but it's bad practice. You're just going to have to git fetch/pull whenever you want the latest version. I'd recommend "watching" this repo for changes and receive notifications upon new commits. Then pull and rebuild your docker image.

I'm still new to all this staff with using git, can you like create a script for me that will be able to download it and replace the files? I don't know how to do it automatically

**Comment by brandongallagher1999** [comment]
https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/update-github-repositories-with-changes-by-others/

**Comment by TomerGamerTV** [comment]
> https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
> 
> https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/update-github-repositories-with-changes-by-others/

i need to rebuild it every single time I update?

**Comment by brandongallagher1999** [comment]
Yes, that's how Docker containers work. You need to build the code repository into an image then you run that isolated image as a container.

**Comment by TomerGamerTV** [comment]
> Yes, that's how Docker containers work. You need to build the code repository into an image then you run that isolated image as a container.

well I was able to make a script that will automatically download build and start it
```
git pull
docker-compose build
docker-compose up
```
do you have discord or something like that so I can give you suggestions?

**Comment by brandongallagher1999** [comment]
That script will work, yes.

My discord is Cryptoguys#9046
